from django.db import models

class CleverCharacters(models.Model):
    school = models.TextField(blank=True, null=True)
    student_id = models.TextField(blank=True, null=True)
    student_name = models.TextField(blank=True, null=True)
    grade = models.IntegerField(blank=True, null=True)
    period = models.TextField(blank=True, null=True)
    course = models.TextField(blank=True, null=True)
    cavg = models.TextField(blank=True, null=True)
    teacher = models.TextField(blank=True, null=True)
    misconducts = models.TextField(blank=True, null=True)
    attendance = models.TextField(blank=True, null=True)
    date_posted = models.DateField()

class Roster(models.Model):
    student_id = student_id = models.IntegerField()
    student = models.TextField(blank=True, null=True)
    grade_level = models.IntegerField()
    course_id = models.TextField(blank=True, null=True)
    section = models.IntegerField()
    period = models.IntegerField()
    course_name = models.TextField(blank=True, null=True)
    cavg = models.IntegerField()
    teacher = models.TextField(blank=True, null=True)
    teacher_id = models.TextField(blank=True, null=True)
    date_posted = models.DateField()

class DataWall(models.Model):
    student = models.TextField(blank=True, null=True)
    grade_level = models.TextField(blank=True, null=True)
    slc = models.TextField(blank=True, null=True)
    student_id = models.IntegerField()
    race = models.TextField(blank=True, null=True)
    gender = models.TextField(blank=True, null=True)
    lunch = models.TextField(blank=True, null=True)
    sped = models.TextField(blank=True, null=True)
    ell = models.TextField(blank=True, null=True)
    demoted = models.TextField(blank=True, null=True)
    birthdate = models.TextField(blank=True, null=True)
    parent = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    city = models.TextField(blank=True, null=True)
    state = models.TextField(blank=True, null=True)
    zip = models.TextField(blank=True, null=True)
    parent_phone = models.TextField(blank=True, null=True)
    on_track = models.TextField(blank=True, null=True)
    credits = models.TextField(blank=True, null=True)
    weighted_gpa = models.TextField(blank=True, null=True)
    class_rank = models.TextField(blank=True, null=True)
    sl_hours = models.TextField(blank=True, null=True)
    nwea_rdg = models.TextField(blank=True, null=True)
    epas_comp = models.TextField(blank=True, null=True)
    last_points = models.TextField(blank=True, null=True)
    current_points = models.TextField(blank=True, null=True)
    slc_current_points = models.TextField(blank=True, null=True)
    trend = models.TextField(blank=True, null=True)
    aca = models.TextField(blank=True, null=True)
    slc_aca = models.TextField(blank=True, null=True)
    att = models.TextField(blank=True, null=True)
    slc_att = models.TextField(blank=True, null=True)
    beh = models.TextField(blank=True, null=True)
    coach = models.TextField(blank=True, null=True)
    action_plan_goal = models.TextField(blank=True, null=True)
    date_posted = models.DateField()
